keys:
  - &admin_rtlong age1yckhkkdjmern0s3enutzllwm7chnzm5f98x09mquz5s8jqmdnv5q0n7vnv
  - &server_optiplex age1nx74q598cz4v5qx2w4l49aj2aescm3755579tdja8ggtqzaz2ggs0fslwk

creation_rules:
  - path_regex: systems/.+?/optiplex/secrets/.*
    key_groups:
      - age:
        - *admin_rtlong
        - *server_optiplex
